#!/usr/bin/env bash
# PreToolUse (Edit|Write|MultiEdit) hook.
# Blocks hand-edits to generated or protected files (exit 2 sends the message back to Claude).
#   - shadcn primitives (frontend/src/components/ui/*): wrap in components/common/ instead
#   - generated API types (*/src/types/api.generated.ts): run `bun run types:api`
#   - generated contract (backend/.contracts/*): run `bun run contract:generate`
#   - drizzle-kit migrations (backend/drizzle/*, backend/src/db/migrations/*): generate, don't hand-edit
#   - env files (.env, .env.*): never written by agents; document vars in .env.example
set -u

file=$(jq -r '.tool_input.file_path // empty')
[ -n "$file" ] || exit 0

deny() {
  echo "Blocked: $1 ($file)" >&2
  exit 2
}

case "$file" in
  */.env.example | */.env.*.example) exit 0 ;;
  */.env | */.env.*) deny "env files are never edited by agents; document the variable in .env.example" ;;
  */frontend/src/components/ui/*) deny "shadcn primitives are not hand-edited; wrap them in src/components/common/" ;;
  */src/types/api.generated.ts) deny "generated file; run 'bun run types:api' after 'bun run contract:generate' in backend/" ;;
  */backend/.contracts/*) deny "generated file; run 'bun run contract:generate' in backend/" ;;
  */backend/drizzle/* | */backend/src/db/migrations/*) deny "migrations are generated by drizzle-kit; change the Drizzle schema and generate" ;;
esac
exit 0
